# Generated by Django 4.2.1 on 2023-05-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'read all books')]},
        ),
    ]
